VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
WPM_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
QMK_SETTINGS = no


MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no